import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import nebulaSidebar from './nebula';

export type SidebarConfig = SidebarsConfig[string];

const sceneSidebar = (dirName: string): SidebarConfig => [
  {
    type: 'autogenerated',
    dirName,
  },
];

const sidebars: SidebarsConfig = {
  nebulaSidebar,
  tutorialsOverviewSidebar: [{ type: 'doc', id: 'tutorials/index' }],
  tutorialsLinuxSidebar: sceneSidebar('tutorials/linux'),
  tutorialsWindowsSidebar: sceneSidebar('tutorials/windows'),
  tutorialsMacosSidebar: sceneSidebar('tutorials/macos'),
  tutorialsDockerSidebar: sceneSidebar('tutorials/docker'),
  tutorialsK8sSidebar: sceneSidebar('tutorials/k8s'),
  tutorialsCiSidebar: sceneSidebar('tutorials/ci'),
  tutorialsJavaSidebar: sceneSidebar('tutorials/java'),
  tutorialsDatabaseSidebar: sceneSidebar('tutorials/database'),
  tutorialsNetworkSidebar: sceneSidebar('tutorials/network'),
  tutorialsOtherSidebar: sceneSidebar('tutorials/other'),
  troubleshootingOverviewSidebar: [{ type: 'doc', id: 'troubleshooting/index' }],
  troubleshootingLinuxSidebar: sceneSidebar('troubleshooting/linux'),
  troubleshootingWindowsSidebar: sceneSidebar('troubleshooting/windows'),
  troubleshootingMacosSidebar: sceneSidebar('troubleshooting/macos'),
  troubleshootingDockerSidebar: sceneSidebar('troubleshooting/docker'),
  troubleshootingK8sSidebar: sceneSidebar('troubleshooting/k8s'),
  troubleshootingCiSidebar: sceneSidebar('troubleshooting/ci'),
  troubleshootingJavaSidebar: sceneSidebar('troubleshooting/java'),
  troubleshootingDatabaseSidebar: sceneSidebar('troubleshooting/database'),
  troubleshootingNetworkSidebar: sceneSidebar('troubleshooting/network'),
  troubleshootingOtherSidebar: sceneSidebar('troubleshooting/other'),
};

export default sidebars;
